### Country Currency Exchange API Tests

# Base URL
@baseUrl = http://localhost:3003

### 1. Test Refresh Countries and Save
POST {{baseUrl}}/countries/refresh
Content-Type: application/json

###

### 2. Get All Countries (after refresh)
GET {{baseUrl}}/countries

###

### 2a. Get Countries filtered by region
GET {{baseUrl}}/countries?region=Africa

###

### 2b. Get Countries filtered by currency
GET {{baseUrl}}/countries?currency=NGN

###

### 2c. Get Countries sorted by GDP descending
GET {{baseUrl}}/countries?sort=gdp_desc

###

### 2d. Get Countries filtered and sorted
GET {{baseUrl}}/countries?region=Africa&currency=NGN&sort=gdp_desc

###

### 3. Get Countries by Name (Search by partial name)
GET {{baseUrl}}/countries/search?name=Åland Islands
# Try other examples:
# GET {{baseUrl}}/countries/search?name=germany
# GET {{baseUrl}}/countries/search?name=jap

###

### 4. Delete Countries by Name (Delete by partial name match)
DELETE {{baseUrl}}/countries/delete?name=afghanistan
# WARNING: This will delete countries matching the name pattern
# Use with caution! Try with test data first
# DELETE {{baseUrl}}/countries/delete?name=vatican

###

### 5. Get Countries Status
GET {{baseUrl}}/countries/status

###

### 6. Get Country Image
GET {{baseUrl}}/countries/image

###

### 7. Test Root Endpoint
GET {{baseUrl}}/

###